apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-TyMemoo
spec:
  displayName: TyMemoo
  author:
    name: yuyan
    website: "https://github.com/likesrt"
  description: "在halo上的typecho"
  logo: "https://www.halo.run/logo"
  homepage: "https://github.com/likesrt/theme-TyMemoo"
  repo: "https://github.com/halo-dev/theme-TyMemoo"
  issues: "https://github.com/halo-dev/theme-TyMemoo/issues"
  settingName: "theme-tymemoo-setting"
  configMapName: "theme-tymemoo-configMap"
  version: "1.0.0"
  requires: ">=2.0.0"
  customTemplates:
    page:
      - name: 友链
        description: 支持可预设文本的友链
        screenshot:
        file: page_links.html
      - name: 关于
        description: 关于模板
        screenshot:
        file: page_about.html